title: Menglan Chen
logo: assets/images/Portrait_20240615_square.png
#description: text below 
show_downloads: true
theme: jekyll-theme-minimal
#jekyll-theme-minimal
#theme options: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
